version: 0.1
os: linux
files:
  - source: /build/libs/crm-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root
