version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - echo "Nothing to do in the pre_build phase..."
  build:
    commands:
      - echo "Build started on `date`"
      - ./gradlew -Pprod clean bootJar
      - zip -r crm-server.zip build/libs/crm-0.0.1-SNAPSHOT.jar scripts/*.sh appspec.yml
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - crm-server.zip
